spring:
  datasource:
    url: jdbc:h2:file:/Users/daiz/testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
  h2:
    console.enabled: true

project:
  secret: secret_phrase_that_can_never_be_guessed